Matrix Addition & Subtraction

In [3]:
import numpy as np

In [6]:
first_matrix = np.random.randn(3,3)

In [7]:
first_matrix

array([[ 1.26725657, -0.25860564,  0.0973862 ],
       [-0.02320712,  0.66317564, -2.1801129 ],
       [-1.13028966, -1.44156108,  0.63674842]])

In [8]:
second_matrix = np.random.randn(3,3)

Matrix Addition

In [9]:
first_matrix + second_matrix

array([[ 0.14967541,  0.95156429, -0.14840228],
       [-2.26535135,  1.37336175, -2.89636143],
       [-0.87153232, -0.72963766,  0.61710559]])

Matrix Subtraction

In [10]:
first_matrix - second_matrix

array([[ 2.38483773, -1.46877558,  0.34317468],
       [ 2.21893712, -0.04701047, -1.46386438],
       [-1.389047  , -2.15348449,  0.65639124]])

Shifting the Matrix

In [12]:
first_matrix + 5 * np.eye(3,3)

array([[ 6.26725657, -0.25860564,  0.0973862 ],
       [-0.02320712,  5.66317564, -2.1801129 ],
       [-1.13028966, -1.44156108,  5.63674842]])