Diagonal And Trace

In [1]:
import numpy as np

In [2]:
matrix_1 = np.matrix([[2, 19],[17, -25]])
matrix_1

matrix([[  2,  19],
        [ 17, -25]])

In [4]:
np.diag(matrix_1)

array([  2, -25])

In [5]:
np.trace(matrix_1)

-23

In [6]:
matrix_2 = np.matrix([[3, 5, 7],[8, -9, 2]])
matrix_2

matrix([[ 3,  5,  7],
        [ 8, -9,  2]])

In [7]:
np.diag(matrix_2)

array([ 3, -9])

In [8]:
np.trace(matrix_2)

-6