Matrix Scalar Multiplication

In [2]:
import numpy as np

In [4]:
first_matrix = np.mat(np.array([[1, 2], [3, 4]]))
first_matrix

matrix([[1, 2],
        [3, 4]])

In [5]:
first_matrix * 5

matrix([[ 5, 10],
        [15, 20]])

In [6]:
5 * first_matrix

matrix([[ 5, 10],
        [15, 20]])

Code Challenge **Check for Distributive Property**

In [7]:
scalar = 0.9
matrix1 = np.mat([[17, 18],[19, 21]])
matrix2 = np.mat([[21, 9],[2, 7]])

scalar * (matrix1 + matrix2)

matrix([[34.2, 24.3],
        [18.9, 25.2]])

In [8]:
scalar * matrix1 + scalar * matrix2

matrix([[34.2, 24.3],
        [18.9, 25.2]])

**Matrix Scalar Multiplication is Linear Operation**