In [14]:
import numpy as np

In [15]:
matrix1 = np.reshape(np.arange(1,13), (3, 4))

In [16]:
matrix2 = matrix1.T

In [17]:
print(matrix1)
print('\n\n')
print(matrix2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [18]:
matrix1 + [10, 20, 30, 40]

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

In [22]:
matrix1 + np.reshape([10, 20, 30],(3,1))

array([[11, 12, 13, 14],
       [25, 26, 27, 28],
       [39, 40, 41, 42]])