In [1]:
import numpy as np

In [2]:
my_matrix = np.mat([[3, 15], [9, 18]])
my_matrix

matrix([[ 3, 15],
        [ 9, 18]])

Symmetric Transpose

In [3]:
my_matrix.T

matrix([[ 3,  9],
        [15, 18]])

In [4]:
np.transpose(my_matrix)

matrix([[ 3,  9],
        [15, 18]])

Asymmetric Transpose

In [6]:
np.transpose(-my_matrix)

matrix([[ -3,  -9],
        [-15, -18]])

Complex Matrix Transpose

In [8]:
complexMat = np.matrix([[2, 9],[3, 1]], dtype = np.complex64)
complexMat

matrix([[2.+0.j, 9.+0.j],
        [3.+0.j, 1.+0.j]], dtype=complex64)

In [10]:
np.conjugate(complexMat).T

matrix([[2.-0.j, 3.-0.j],
        [9.-0.j, 1.-0.j]], dtype=complex64)