<h1>Zoo Of Matrices</h1>

In [1]:
import numpy as np

Square Vs Rectangular Matrix

In [3]:
np.mat(np.random.randn(4,4))

matrix([[ 0.72629375,  0.31075131, -1.79070375, -0.11046482],
        [ 1.14260559,  0.13990376,  0.77444226, -0.31667035],
        [ 0.76045924,  0.65327688,  0.37208337, -0.4507531 ],
        [-0.75482636,  1.25291744, -0.02620734,  0.57869209]])

In [4]:
np.mat(np.random.randn(4,5))

matrix([[ 0.9932685 , -1.60156864, -0.55928414, -0.20013729,  2.20498676],
        [-0.05300907,  2.6075429 ,  1.21341068, -0.54355789,  1.50185854],
        [ 0.38822371, -0.26151475, -0.30053401,  0.51852041,  0.34231157],
        [-0.10501382,  0.41639961,  0.16939514,  1.85831137, -0.76863682]])

Identity Matrix

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Zero Matrix

In [7]:
np.mat(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Digaonal Matrix

In [8]:
np.mat(np.diag([10, 12, 17, 19, 38]))

matrix([[10,  0,  0,  0,  0],
        [ 0, 12,  0,  0,  0],
        [ 0,  0, 17,  0,  0],
        [ 0,  0,  0, 19,  0],
        [ 0,  0,  0,  0, 38]])

Upper and Lower Triangular Matrix

In [9]:
tempMat = np.random.randn(4,4)

Upper Triangular

In [12]:
np.triu(tempMat)

array([[-0.90538752,  0.02859443, -0.12022767, -0.51917662],
       [ 0.        , -0.06377245,  0.66846973,  1.44848547],
       [ 0.        ,  0.        ,  0.11717849, -0.73092671],
       [ 0.        ,  0.        ,  0.        , -0.51021647]])

Lower Triangular

In [14]:
np.tril(tempMat)

array([[-0.90538752,  0.        ,  0.        ,  0.        ],
       [-1.73018962, -0.06377245,  0.        ,  0.        ],
       [-0.31957194,  0.60049953,  0.11717849,  0.        ],
       [-0.35565115, -0.00458747,  0.3438775 , -0.51021647]])

Concatenated Matrix

In [17]:
A = np.random.randn(4,5)
A

array([[-0.22479951, -0.45537717,  1.37455898,  1.56732569,  1.20098001],
       [ 1.31004134,  0.31690136,  0.07070384,  0.06977316,  0.43076315],
       [ 0.11907967,  0.23103893,  1.15153851,  0.55587681,  2.02503193],
       [-0.727951  ,  0.27469764,  0.11498546,  0.98883104, -0.90323801]])

In [19]:
B = np.random.randn(4,2)
B

array([[-0.03307295, -0.47973273],
       [-1.24384367, -1.4488691 ],
       [-0.46917128,  0.41940707],
       [-1.12344028,  1.332909  ]])

In [23]:
np.concatenate((A,B), axis = 1)

array([[-0.22479951, -0.45537717,  1.37455898,  1.56732569,  1.20098001,
        -0.03307295, -0.47973273],
       [ 1.31004134,  0.31690136,  0.07070384,  0.06977316,  0.43076315,
        -1.24384367, -1.4488691 ],
       [ 0.11907967,  0.23103893,  1.15153851,  0.55587681,  2.02503193,
        -0.46917128,  0.41940707],
       [-0.727951  ,  0.27469764,  0.11498546,  0.98883104, -0.90323801,
        -1.12344028,  1.332909  ]])