<h1>The Outer Product of Vectors</h1>
<img src="https://i.ibb.co/Zcbj1VB/d.png" alt="d" border="0">
<p>You can think this product in either row or column perspective</p>

**Outer Product in Python Code**

In [4]:
#import numpy package
import numpy as np  

#vectors
v1 = np.array([3, 2, -4, 5, -6], dtype = np.float64)
v2 = np.array([-6, 4, -3, 0, 9], dtype= np.float64) 

#Staright forward calculations
outer_product = np.outer(v1, v2)

#Not so Straight forward calculations
output = np.zeros((len(v1), len(v2)))
for i in range(len(v1)):
    for j in range(len(v2)):
        output[i][j] = v1[i] * v2[j]

print("Output Using Straight Forward Method :\n{}\n".format(outer_product))
print("Output Using Not so Straight Forward Method :\n{}".format(output))



Output Using Straight Forward Method :
[[-18.  12.  -9.   0.  27.]
 [-12.   8.  -6.   0.  18.]
 [ 24. -16.  12.  -0. -36.]
 [-30.  20. -15.   0.  45.]
 [ 36. -24.  18.  -0. -54.]]

Output Using Not so Straight Forward Method :
[[-18.  12.  -9.   0.  27.]
 [-12.   8.  -6.   0.  18.]
 [ 24. -16.  12.  -0. -36.]
 [-30.  20. -15.   0.  45.]
 [ 36. -24.  18.  -0. -54.]]
