<h1>Challenge 1 Vectors Section</h1>
<ol>
<li>Create A 4 X 6 Matrix of random numbers</li>
<li>Use Dot Products to compute dot products between corresponding columns</li>
<ul>

**Importing the Libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [16]:
#generate a random matrix 

#1st Sub Challenge
matrix1 = np.random.randn(4,6)
matrix2 = np.random.randn(4,6)

print("Matrix 1 : \n{}".format(matrix1))
print("\n")
print("Matrix 2 : \n{}".format(matrix2))

#Empty list for storing Dot Products
dps = np.zeros(6)

#2nd Sub Challenge
for i in range(6):
    dps[i] = np.dot(matrix1[:,i],matrix2[:,i])

print("\nThe Dot Products Are : \n{}".format(dps))

Matrix 1 : 
[[ 7.03029775e-01 -5.14880238e-01 -1.22682704e+00  3.82685344e-01
  -2.70277249e-01  1.98717331e+00]
 [-2.80677624e-01 -1.23926932e-01 -6.74541690e-01  1.00730452e+00
   2.98504545e-01  1.68045743e-01]
 [ 1.75702398e-01 -6.02264605e-01  2.54729338e-01 -7.55486447e-01
  -2.26017240e-01  1.33929936e+00]
 [ 1.18211346e+00  2.44297200e-01 -8.89258975e-02 -1.98787317e-01
   1.97876784e-04  1.50289623e+00]]


Matrix 2 : 
[[-1.33499403 -0.46626898 -0.64730608 -0.54701835 -1.02746672 -0.23094972]
 [-0.11792717 -0.17123797  0.21651072 -1.27024525  2.13721407 -0.82427887]
 [ 0.62334746 -1.55665679  0.47014477 -1.50856917  1.84108667 -0.22666735]
 [ 0.21350517 -0.07319609 -0.81876751  1.9376836   0.11303224  1.39979994]]

The Dot Products Are : 
[-0.54353005  1.18093136  0.8406564  -0.73434305  0.49957403  1.20272494]
