<h1>Additive & Multiplicative Symmetric Matrices</h1>

In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [10]:
##The Addtitive Method

#Specify Sizes
m = 5
n = 5

#Create Matrices
matrix = np.random.randint(5, 10, (m, n))
S = (matrix + matrix.T)/2

print(S-S.T)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
##The Multiplicative Method

#specify size
m = 6
n = 5

#create matrices
matrix = np.random.randint(-10, 10, (m, n))
S = matrix@matrix.T

print(S-S.T)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
