In [1]:
import numpy as np

In [2]:
matrix1 = np.random.randint(1, 100, (3,3))
matrix2 = np.random.randint(1, 900, (3, 3))

In [3]:
matrix1

array([[85, 44, 57],
       [24, 67, 92],
       [62, 90, 28]])

In [4]:
matrix2

array([[423, 335, 734],
       [470, 859, 470],
       [691, 715, 765]])

In [17]:
final_list  = []

for i in matrix1.T:
  temp_list = []
  for j in matrix2:
    temp_list.append(i * j)
  final_list.append(temp_list)

In [25]:
final_array = np.array(final_list)

In [26]:
sum = np.zeros((3,3))

for i in final_array:
  sum += np.array(i)

In [27]:
print(sum)

[[ 78678.  61305. 132120.]
 [ 87420. 157197.  84600.]
 [128526. 130845. 137700.]]


In [28]:
np.matmul(matrix1, matrix2)

array([[ 96022, 107026, 126675],
       [105214, 131373, 119486],
       [ 87874, 118100, 109228]])

In [24]:
for i in matrix2:
  print(i)

[423 335 734]
[470 859 470]
[691 715 765]


In [31]:
m = 4
n = 6

matrix1 = np.random.randn(m,n)
matrix2 = np.random.randn(n, m)

result = np.zeros((m, m))

for i in range(n):
  result += np.outer(matrix1[:, i], matrix2[i, :])

print(result) 
print("\n\n\n\n")
print(matrix1@matrix2)
print("\n\n\n\n")
print(matrix1@matrix2 - result)


[[ 0.0302157  -0.31099203 -0.72654288  3.00005721]
 [ 0.1024627   2.38711147 -1.60915857  0.12806246]
 [-0.43807288  1.14802855 -3.63797803  1.35008133]
 [ 3.02568339  0.39947686  0.74836666 -3.96045679]]





[[ 0.0302157  -0.31099203 -0.72654288  3.00005721]
 [ 0.1024627   2.38711147 -1.60915857  0.12806246]
 [-0.43807288  1.14802855 -3.63797803  1.35008133]
 [ 3.02568339  0.39947686  0.74836666 -3.96045679]]





[[-1.38777878e-17  0.00000000e+00 -1.11022302e-16  4.44089210e-16]
 [ 1.38777878e-17 -4.44089210e-16  0.00000000e+00 -5.55111512e-17]
 [-1.11022302e-16  0.00000000e+00  4.44089210e-16  2.22044605e-16]
 [ 0.00000000e+00 -1.11022302e-16  0.00000000e+00  0.00000000e+00]]
