<h1>Code Challenge 4</h1>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
matrix1 = np.random.randint(-10, 10, (5, 5))
print(matrix1)
matrix2 = np.random.randint(-10, 10, (3, 4))
print(matrix2)
matrix3 = np.random.randint(-10, 10, (3,4))
print(matrix3)

[[  6   5   1  -8   3]
 [ -9   1  -8  -1   8]
 [ -2   5   9  -2  -7]
 [ -5   7 -10   5  -3]
 [ -6   0  -5  -3  -9]]
[[-2 -2  1  7]
 [ 5  7  2  4]
 [ 1  1 -7  2]]
[[-2 -8  5  4]
 [-2  9  3  9]
 [-7  2 -9  2]]


In [5]:
sym1 = matrix1 + matrix1.T
sym1

array([[ -4,   6,  14,   1,  -5],
       [  6,   4,  -4, -15,   7],
       [ 14,  -4, -18,  -5,   3],
       [  1, -15,  -5, -10,  -6],
       [ -5,   7,   3,  -6,  -6]])

In [7]:
sym2 = matrix2@matrix2.T
sym2

array([[114, -21,  -1],
       [-21, 122, -49],
       [ -1, -49,  86]])

In [9]:
sym3 = matrix3@matrix3.T
sym3

array([[109, -17, -39],
       [-17, 175,  23],
       [-39,  23, 138]])

In [10]:
#sum of symmetric matrices
sym2 + sym3

array([[223, -38, -40],
       [-38, 297, -26],
       [-40, -26, 224]])

In [11]:
#matrix multiplication
sym2@sym3

array([[12822, -5636, -5067],
       [-2452, 20580, -3137],
       [-2630, -6580, 10780]])

In [12]:
#hadmard multiplication
sym2*sym3

array([[12426,   357,    39],
       [  357, 21350, -1127],
       [   39, -1127, 11868]])

**Sum of Two Symmteric Matirces Results into a Symmteric matrix**<br>
**Hadmarad Multiplication of Two Symmteric Matrices Output a Symmteric Matrix**<br>
**Multiplication of Two Symmteric Matrix does not result into a Symmteric Matrix**