<h1>Code Challenge 5</h1>

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
matrix1 = np.random.randint(1, 8, (4, 4))
matrix2 = np.eye(4)

matrix1

array([[1, 4, 2, 6],
       [6, 6, 5, 7],
       [2, 7, 7, 1],
       [6, 5, 3, 4]])

In [15]:
matrix2 = matrix2 * np.random.randint(-10, 15, (4, 4))
matrix2

array([[12., -0.,  0., -0.],
       [ 0., 13., -0., -0.],
       [ 0.,  0.,  7., -0.],
       [-0.,  0., -0., 13.]])

In [16]:
#Matrix Multiplication of Matrix 1

matrix1@matrix1

array([[ 65,  72,  54,  60],
       [ 94, 130,  98, 111],
       [ 64, 104,  91,  72],
       [ 66,  95,  70,  90]])

In [17]:
#Hadmarad Multiplication of Matrix1

matrix1*matrix1

array([[ 1, 16,  4, 36],
       [36, 36, 25, 49],
       [ 4, 49, 49,  1],
       [36, 25,  9, 16]])

In [18]:
#Matrix Multiplication of Matrix 2

matrix2@matrix2

array([[144.,   0.,   0.,   0.],
       [  0., 169.,   0.,   0.],
       [  0.,   0.,  49.,   0.],
       [  0.,   0.,   0., 169.]])

In [19]:
#Hadmarad Multiplication of Matrix 2

matrix2*matrix2

array([[144.,   0.,   0.,   0.],
       [  0., 169.,   0.,   0.],
       [  0.,   0.,  49.,   0.],
       [  0.,   0.,   0., 169.]])