In [2]:
import numpy as np

In [3]:
m = 4
n = 3
k = 6

matrix1 = np.random.randn(m, n)
matrix2 = np.random.randn(n, k)
matirx3 = np.random.randn(m, k)

In [4]:
np.matmul(matrix1, matrix2)

array([[-1.51536911,  2.18509346, -3.48820648, -0.31242429,  0.97598108,
        -1.06608162],
       [ 0.75297916, -0.55404846,  4.17041799, -0.47018393,  1.10192706,
         0.58458414],
       [-0.59774565,  4.78197185,  0.39679946,  1.54020739,  4.53138907,
         0.42725947],
       [ 1.17962032, -1.0982441 ,  2.45057071,  0.70714081, -0.37282288,
         0.97493681]])

In [12]:
np.matmul(matrix1, matrix1.T)

array([[ 5.89918926, -3.39105336,  3.81302278, -4.20189281],
       [-3.39105336,  4.29052629,  0.29458826,  2.30748396],
       [ 3.81302278,  0.29458826,  7.66174081, -2.35266374],
       [-4.20189281,  2.30748396, -2.35266374,  3.08724246]])

In [14]:
np.matmul(matrix2.T, matrix2)

array([[ 0.49583584, -0.07614598,  0.85661842,  0.59554789,  0.08884491,
         0.50268899],
       [-0.07614598,  3.71326987, -0.28161907,  2.18594623,  3.05101196,
         0.7732699 ],
       [ 0.85661842, -0.28161907,  4.11356597, -0.08143223,  1.25466232,
         0.76204388],
       [ 0.59554789,  2.18594623, -0.08143223,  2.5108857 ,  1.5174918 ,
         1.15490169],
       [ 0.08884491,  3.05101196,  1.25466232,  1.5174918 ,  3.12474582,
         0.76065515],
       [ 0.50268899,  0.7732699 ,  0.76204388,  1.15490169,  0.76065515,
         0.70700851]])

In [15]:
matirx3@matrix2.T

array([[-0.59094808, -2.16810366,  3.58195157],
       [ 3.74505521, -2.52856339, -0.3576218 ],
       [-1.4535276 ,  1.18194978,  1.09883489],
       [ 0.64477502, -0.00735128, -0.09128662]])

In [20]:
np.matmul(matirx3, matrix2.T)

array([[-0.59094808, -2.16810366,  3.58195157],
       [ 3.74505521, -2.52856339, -0.3576218 ],
       [-1.4535276 ,  1.18194978,  1.09883489],
       [ 0.64477502, -0.00735128, -0.09128662]])