<h1> Multiplication of Symmetric Matrices</h1>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
DiagSame = np.eye(10,dtype = np.int32)
DiagSame = (DiagSame - 1)*-1

matrix1 = DiagSame * np.random.randint(-10, 10 , (10, 10)) + 7
matrix1 = matrix1 + matrix1.T
matrix1

array([[14,  9,  7,  9, 16, -1,  2,  5,  4, 15],
       [ 9, 14, 23, 28, -2, 16, 24, 15, 11,  4],
       [ 7, 23, 14, 26, 30, 17, 21, 27, 15,  3],
       [ 9, 28, 26, 14, 21, 14, -1, 20,  3,  7],
       [16, -2, 30, 21, 14, 15, 19,  4, 15, 11],
       [-1, 16, 17, 14, 15, 14,  6, 17, 16, 27],
       [ 2, 24, 21, -1, 19,  6, 14, 17, 14, 21],
       [ 5, 15, 27, 20,  4, 17, 17, 14, 25, 15],
       [ 4, 11, 15,  3, 15, 16, 14, 25, 14, 29],
       [15,  4,  3,  7, 11, 27, 21, 15, 29, 14]])

In [3]:
DiagSame2 = np.eye(10,dtype = np.int32)
DiagSame2 = (DiagSame2 - 1)*-1

matrix2 = DiagSame2 * np.random.randint(-10, 10 , (10, 10)) + 5
matrix2 = matrix2 + matrix2.T

In [4]:
matrix2 

array([[10,  7, -6, 23,  0, 17,  8, 13, 12,  3],
       [ 7, 10, 11, 10,  4, 13, 17, 24,  8, 13],
       [-6, 11, 10, 14,  9, -1,  7, 15,  3,  5],
       [23, 10, 14, 10, 10,  4, -2, -3, 11,  6],
       [ 0,  4,  9, 10, 10,  5, 15,  2,  3, 12],
       [17, 13, -1,  4,  5, 10, 13, 16,  5,  7],
       [ 8, 17,  7, -2, 15, 13, 10,  5,  3,  5],
       [13, 24, 15, -3,  2, 16,  5, 10, -6, -1],
       [12,  8,  3, 11,  3,  5,  3, -6, 10, 10],
       [ 3, 13,  5,  6, 12,  7,  5, -1, 10, 10]])

In [5]:
matrix1@matrix2

array([[ 525,  787,  532,  871,  576,  685,  655,  513,  569,  628],
       [1497, 1844, 1134, 1045, 1074, 1209,  961, 1166,  803,  835],
       [1742, 2198, 1580, 1275, 1313, 1629, 1569, 1389,  852, 1283],
       [ 999, 1613, 1222, 1274,  884, 1163, 1333, 1573,  674, 1030],
       [1121, 1565,  880, 1359, 1157,  983,  977,  849,  907,  922],
       [1102, 1711, 1149,  996, 1073, 1064, 1090,  915,  782, 1095],
       [ 705, 1660, 1113,  985, 1033, 1147, 1308, 1189,  645, 1090],
       [1405, 1939, 1183, 1240, 1166, 1198, 1115, 1110,  945, 1103],
       [1060, 1928, 1068,  881, 1089, 1298, 1203, 1025,  661, 1015],
       [1533, 1774,  683, 1031,  958, 1413, 1153,  836,  869,  995]])

In [9]:
matrix1.shape

(10, 10)

In [8]:
matrix2.shape

(10, 10)