<h1>Vector Matrix Multiplication</h1>

In [1]:
import numpy as np

Matrix N

In [4]:
m = 4
N = np.random.randint(-10, 10, (m,m))
N

array([[-10,  -8,   5,  -4],
       [ -4,  -7,  -5,  -9],
       [  4,  -1,  -3,   8],
       [ -9,  -7,   5,  -4]])

Matrix S : Scaled Symmetric Matrix

In [5]:
S = np.round(N@N.T / m**2)
S

array([[13.,  7., -5., 12.],
       [ 7., 11., -4.,  6.],
       [-5., -4.,  6., -5.],
       [12.,  6., -5., 11.]])

In [6]:
N*N.T

array([[100,  32,  20,  36],
       [ 32,  49,   5,  63],
       [ 20,   5,   9,  40],
       [ 36,  63,  40,  16]])

vector m

In [17]:
w = np.array([-1, 0, 1, 2])

In [18]:
w

array([-1,  0,  1,  2])

Multiplication of matrix with vector where matrix is not symmetric

In [19]:
print(N@w)
print("\n\n")
print(N.T@w)
print("\n\n")
print(w@N)
print("\n\n")
print(w.T@N.T)
print("\n\n")
print(w.T@N)

[  7 -19   9   6]



[-4 -7  2  4]



[-4 -7  2  4]



[  7 -19   9   6]



[-4 -7  2  4]


Multiplication of matrix with vector where matrix is symmetric

In [22]:
print(S@w)
print("\n\n")
print(S.T@w)
print("\n\n")
print(w@S)
print("\n\n")
print(w.T@S.T)
print("\n\n")
print(w.T@S)

[6. 1. 1. 5.]



[6. 1. 1. 5.]



[6. 1. 1. 5.]



[6. 1. 1. 5.]



[6. 1. 1. 5.]


In [25]:
np.linalg.inv(np.matrix([[2, 4], [2, 1]])) * np.matrix([22, 10]).T

matrix([[3.],
        [4.]])